$(document).ready(function(){
  $(window).scroll(function(){
    if($(document).scrollTop()>0){
      $("#header").addClass("scroll");
    }else{
      $("#header").removeClass("scroll");
    }
  });
});