# Generated by Django 2.2 on 2020-02-05 06:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(default=datetime.datetime(2020, 2, 5, 15, 7, 37, 709672), editable=False, verbose_name='등록일')),
                ('customer_join_date', models.DateField(verbose_name='계약일')),
                ('customer_end_date', models.DateField(verbose_name='해임일')),
                ('customer_ing', models.CharField(max_length=50, verbose_name='계약상태')),
                ('join_category', models.CharField(max_length=50, verbose_name='계약구분')),
                ('customer_category', models.CharField(max_length=50, verbose_name='회원구분')),
                ('company_ing', models.CharField(max_length=50, verbose_name='회원상태')),
                ('company_name', models.CharField(max_length=50, verbose_name='거래처명')),
                ('bizcode', models.CharField(max_length=50, verbose_name='사업자등록번호')),
                ('bizsub1', models.CharField(max_length=50, verbose_name='업종')),
                ('bizsub2', models.CharField(max_length=50, verbose_name='종목')),
                ('biz_start_date', models.DateField(verbose_name='개업일')),
                ('biz_end_date', models.DateField(verbose_name='폐업일')),
                ('biz_stop_date', models.DateField(verbose_name='휴업일')),
                ('customer_name', models.CharField(max_length=50, verbose_name='대표자')),
                ('customer_reg_number', models.CharField(max_length=50, verbose_name='주민번호')),
                ('customer_phone', models.CharField(max_length=50, verbose_name='전화번호')),
                ('company_address', models.CharField(max_length=50, verbose_name='주소')),
                ('company_co_owner', models.BooleanField(verbose_name='공동대표여부')),
                ('sales1', models.CharField(max_length=50, verbose_name='영업자(주)')),
                ('sales2', models.CharField(max_length=50, verbose_name='영업자(부)')),
                ('sales2_code', models.CharField(max_length=50, verbose_name='영업자(부)구분')),
                ('pay_start_date', models.DateField(verbose_name='결제시작일')),
                ('pay_category', models.CharField(max_length=50, verbose_name='결제방법')),
                ('pay_name', models.CharField(max_length=50, verbose_name='예금주')),
                ('pay_bank_card', models.CharField(max_length=50, verbose_name='결제사')),
                ('pay_number', models.CharField(max_length=50, verbose_name='통장/카드번호')),
                ('card_day', models.CharField(max_length=50, verbose_name='유효기간일')),
                ('card_year', models.CharField(max_length=50, verbose_name='유효기간월')),
                ('month_pay', models.IntegerField(verbose_name='월수수료')),
                ('year_pay', models.CharField(max_length=50, verbose_name='조정수수료')),
                ('add_document', models.CharField(max_length=50, verbose_name='첨부파일')),
                ('upload', models.FileField(upload_to=None)),
                ('customer_memo', models.CharField(max_length=50, verbose_name='회원메모')),
                ('company_memo', models.CharField(max_length=50, verbose_name='회사메모')),
                ('pay_memo', models.CharField(max_length=50, verbose_name='결제메모')),
                ('memo', models.TextField(max_length=50, verbose_name='비고')),
                ('upload_paysite', models.BooleanField(verbose_name='결제등록여부')),
                ('customer_used', models.BooleanField(verbose_name='사용여부')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('relation_company', models.ManyToManyField(related_name='_customers_relation_company_+', to='contact.Customers')),
            ],
        ),
        migrations.CreateModel(
            name='Depts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=50, verbose_name='부서')),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50, verbose_name='직책')),
            ],
        ),
        migrations.CreateModel(
            name='Ranks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=50, verbose_name='직급')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=50, verbose_name='팀')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(default=datetime.datetime(2020, 2, 5, 15, 7, 37, 709672), editable=False, verbose_name='등록일')),
                ('user_join_date', models.DateField(verbose_name='입사일')),
                ('user_id', models.CharField(max_length=50, verbose_name='회원아이디')),
                ('user_password', models.CharField(max_length=50, verbose_name='비밀번호')),
                ('user_name', models.CharField(max_length=50, verbose_name='회원이름')),
                ('user_reg_number', models.CharField(max_length=50, verbose_name='주민번호')),
                ('phone_number', models.CharField(max_length=50, verbose_name='전화번호')),
                ('e_mail', models.EmailField(max_length=254, verbose_name='이메일')),
                ('authent', models.CharField(max_length=50, verbose_name='사용자등급')),
                ('used', models.BooleanField(max_length=50, verbose_name='사용여부')),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='contact.Depts')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='contact.Positions')),
                ('rank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='contact.Ranks')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='contact.Teams')),
            ],
        ),
        migrations.CreateModel(
            name='Payinformations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(default=datetime.datetime(2020, 2, 5, 15, 7, 37, 712719), editable=False, verbose_name='등록일')),
                ('member_num', models.CharField(max_length=50, verbose_name='회원번호')),
                ('pay_start_date', models.DateField(verbose_name='결제시작일')),
                ('pay_end_date', models.DateField(verbose_name='결제종료일')),
                ('join_date', models.DateField(verbose_name='가입일')),
                ('payinfo_used', models.BooleanField(verbose_name='사용여부')),
                ('pay_day', models.CharField(max_length=50, verbose_name='결제일')),
                ('pay_category', models.CharField(max_length=50, verbose_name='결제방법')),
                ('pay_account_holder', models.CharField(max_length=50, verbose_name='예금주')),
                ('pay_company', models.CharField(max_length=50, verbose_name='결제사')),
                ('pay_number', models.CharField(max_length=50, verbose_name='결제번호')),
                ('card_limited_day', models.CharField(max_length=50, verbose_name='카드유효기간')),
                ('payment_month', models.IntegerField(verbose_name='월수수료')),
                ('pay_memo', models.TextField(max_length=50, verbose_name='결제메모')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payinformations', to='contact.Customers')),
            ],
        ),
        migrations.CreateModel(
            name='pay_results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(default=datetime.datetime(2020, 2, 5, 15, 7, 37, 713717), editable=False, verbose_name='등록일')),
                ('pay_date', models.DateField(verbose_name='결제일')),
                ('payment', models.IntegerField(verbose_name='결제수수료')),
                ('pay_memo', models.CharField(max_length=50, verbose_name='결제메모')),
                ('pay_category', models.CharField(max_length=50, verbose_name='결제구분')),
                ('payinformation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_results', to='contact.Payinformations')),
            ],
        ),
        migrations.CreateModel(
            name='Co_owners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(default=datetime.datetime(2020, 2, 5, 15, 7, 37, 711721), editable=False, verbose_name='등록일')),
                ('co_owner_name', models.CharField(max_length=50, verbose_name='이름')),
                ('co_owner_reg_number', models.CharField(max_length=50, verbose_name='주민번호')),
                ('co_owner_phone', models.CharField(max_length=50, verbose_name='전화번호')),
                ('share_per', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='지분율')),
                ('co_owner_rank', models.CharField(max_length=50, verbose_name='순위')),
                ('co_owner_memo', models.TextField(max_length=50, verbose_name='공동사업자메모')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_owners', to='contact.Customers')),
            ],
        ),
    ]
