# Generated by Django 2.2 on 2020-02-07 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='co_owners',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 9, 34, 2, 463674), editable=False, verbose_name='등록일'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 9, 34, 2, 448055), editable=False, verbose_name='등록일'),
        ),
        migrations.AlterField(
            model_name='pay_results',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 9, 34, 2, 463674), editable=False, verbose_name='등록일'),
        ),
        migrations.AlterField(
            model_name='payinformations',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 9, 34, 2, 463674), editable=False, verbose_name='등록일'),
        ),
        migrations.AlterField(
            model_name='users',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 9, 34, 2, 448055), editable=False, verbose_name='등록일'),
        ),
    ]
